# Regenerates PATCHES.diff: every file under gridplayer/ that differs from the
# pristine upstream snapshot in .upstream/gridplayer (GridPlayer 0.5.5).
#
# Superseded by git: `git diff` describes the same change and, unlike this
# script, also covers the files that only exist here. Kept because a flat patch
# is convenient to read; PATCHES.diff itself is gitignored.
#
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads BOM-less .ps1
# files using the system ANSI codepage, so non-ASCII text here gets mangled and
# can break the parser (a stray quote from a mangled byte is enough).

$ErrorActionPreference = 'Stop'

$root     = $PSScriptRoot
$pristine = Join-Path $root '.upstream\gridplayer'
$patched  = Join-Path $root 'gridplayer'
$out      = Join-Path $root 'PATCHES.diff'

if (-not (Test-Path $pristine)) {
    throw ".upstream snapshot missing at $pristine"
}

$upstreamFiles = Get-ChildItem $pristine -Recurse -File -Filter '*.py' |
    ForEach-Object { $_.FullName.Substring($pristine.Length + 1) }

$changed = @()
foreach ($rel in $upstreamFiles) {
    $a = Join-Path $pristine $rel
    $b = Join-Path $patched  $rel

    if (-not (Test-Path $b)) { $changed += $rel; continue }

    $ha = (Get-FileHash $a -Algorithm SHA256).Hash
    $hb = (Get-FileHash $b -Algorithm SHA256).Hash
    if ($ha -ne $hb) { $changed += $rel }
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# GridPlayer 0.5.5 -> MOD patch')
[void]$sb.AppendLine('# Generated by _mkpatch.ps1 (per-file SHA256 compare against .upstream/gridplayer)')
[void]$sb.AppendLine("# Files differing from upstream: $($changed.Count)")
[void]$sb.AppendLine('')

foreach ($rel in ($changed | Sort-Object)) {
    $a = Join-Path $pristine $rel
    $b = Join-Path $patched  $rel

    if (-not (Test-Path $b)) {
        [void]$sb.AppendLine("### missing in MOD: gridplayer/$rel")
        [void]$sb.AppendLine('')
        continue
    }

    $d = & git.exe -c core.autocrlf=false -c core.safecrlf=false diff --no-index --no-color $a $b 2>$null
    $d = $d | ForEach-Object {
        $_ -replace [regex]::Escape($a), "upstream/gridplayer/$rel" `
           -replace [regex]::Escape($b), "gridplayer/$rel"
    }
    foreach ($line in $d) { [void]$sb.AppendLine($line) }
}

[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

Write-Host "PATCHES.diff written: $((Get-Item $out).Length) bytes"
Write-Host "changed files ($($changed.Count)):"
$changed | Sort-Object | ForEach-Object { Write-Host "  $_" }
